<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getOrderList, getOrderDetail, cancelOrder } from '../../../api/user/orders'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
const router = useRouter()
const loading = ref(false); const orders = ref<any[]>([]); const total = ref(0); const currentPage = ref(1); const pageSize = ref(10); const detailVisible = ref(false); const detail = ref<any>(null)
const statuses: Record<number, string> = { 10: '待支付', 20: '待接单', 30: '备餐中', 40: '配送中', 50: '已完成', 60: '已取消', 70: '退款中', 80: '已退款' }
const tags: Record<number, any> = { 10: 'warning', 20: 'primary', 30: 'primary', 40: 'warning', 50: 'success', 60: 'info', 70: 'warning', 80: 'info' }
const fetchOrders = async () => { loading.value = true; try { const res = await getOrderList({ page: currentPage.value, size: pageSize.value }); orders.value = res.data?.list || []; total.value = res.data?.total || 0 } catch { ElMessage.error('获取订单失败') } finally { loading.value = false } }
const showDetail = async (row: any) => { try { const res = await getOrderDetail(row.id); const payload = res.data || row; detail.value = payload.order || payload; detailVisible.value = true } catch { ElMessage.error('获取订单详情失败') } }
const cancel = async (row: any) => { try { await ElMessageBox.confirm('未接单订单可以取消，确定继续吗？', '取消订单'); await cancelOrder(row.id); ElMessage.success('订单已取消'); fetchOrders() } catch {} }
onMounted(fetchOrders)
</script>
<template><div class="page-container"><div class="card-panel"><div class="card-header"><h3>我的订单</h3></div><el-table v-loading="loading" :data="orders" border><el-table-column prop="orderNo" label="订单号" min-width="180" /><el-table-column label="金额" width="120"><template #default="{ row }">¥{{ row.payAmount }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="tags[row.orderStatus]">{{ statuses[row.orderStatus] || '未知状态' }}</el-tag></template></el-table-column><el-table-column prop="createTime" label="下单时间" width="180" /><el-table-column label="操作" width="250" fixed="right"><template #default="{ row }"><el-button size="small" @click="showDetail(row)">查看详情</el-button><el-button v-if="row.orderStatus === 10 || row.orderStatus === 20" size="small" type="danger" @click="cancel(row)">取消订单</el-button><el-button v-if="row.orderStatus === 40" size="small" type="primary" @click="router.push(`/user/delivery/${row.id}`)">配送跟踪</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @current-change="fetchOrders" /></div></div><el-dialog v-model="detailVisible" title="订单详情" width="620px"><el-descriptions v-if="detail" :column="2" border><el-descriptions-item label="订单号">{{ detail.orderNo }}</el-descriptions-item><el-descriptions-item label="状态">{{ statuses[detail.orderStatus] }}</el-descriptions-item><el-descriptions-item label="实付金额">¥{{ detail.payAmount }}</el-descriptions-item><el-descriptions-item label="收件人">{{ detail.receiverName }} {{ detail.receiverPhone }}</el-descriptions-item><el-descriptions-item label="收货地址" :span="2">{{ detail.deliveryAddress }}</el-descriptions-item><el-descriptions-item label="备注" :span="2">{{ detail.remark || '无' }}</el-descriptions-item><el-descriptions-item label="创建时间" :span="2">{{ detail.createTime }}</el-descriptions-item></el-descriptions></el-dialog></div></template>
<style scoped>.page-container{animation:fadeIn .3s ease}.card-panel{background:var(--bs-card-bg);border-radius:var(--bs-radius-md);box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}.card-header{margin-bottom:20px}.card-header h3{margin:0;color:var(--bs-text-title)}.pager{display:flex;justify-content:flex-end;margin-top:16px}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
