<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getMembershipPlans, getMembershipStatus, getMembershipHistory, buyMembership } from '../../../api/user/membership'
import { ElMessage, ElMessageBox } from 'element-plus'
const loading=ref(false), plans=ref<any[]>([]), current=ref<any>(null), history=ref<any[]>([])
const load=async()=>{loading.value=true;try{const [p,s,h]=await Promise.all([getMembershipPlans(),getMembershipStatus(),getMembershipHistory()]);plans.value=p.data||[];current.value=s.data;history.value=h.data||[]}catch{ElMessage.error('加载会员信息失败')}finally{loading.value=false}}
const buy=async(plan:any)=>{try{await ElMessageBox.confirm(`确定购买${plan.planName}吗？价格 ¥${plan.price}`,'购买确认');await buyMembership(plan.id);ElMessage.success('会员购买成功');load()}catch{}}
onMounted(load)
</script>
<template><div class="page"><div v-if="current" class="panel current"><div><span class="muted">当前会员</span><h2>{{current.planName||'会员'}}</h2><p>{{current.startTime}} 至 {{current.endTime}}</p></div><el-tag :type="current.status===10?'success':'info'">{{current.status===10?'有效':'已过期'}}</el-tag></div><div class="panel"><header><h3>会员方案</h3></header><div v-loading="loading" class="plans"><div v-for="plan in plans" :key="plan.id" class="plan"><h3>{{plan.planName}}</h3><p>{{plan.benefits||'享受平台会员权益'}}</p><strong>¥{{plan.price}}</strong><small>{{plan.validDays}}天有效</small><el-button type="primary" :disabled="current?.status===10" @click="buy(plan)">{{current?.status===10?'已有有效会员':'立即购买'}}</el-button></div></div><el-empty v-if="!loading&&!plans.length" description="暂无会员方案"/></div><div class="panel"><header><h3>购买记录</h3></header><el-table :data="history" border><el-table-column prop="membershipType" label="类型"/><el-table-column prop="payAmount" label="金额"/><el-table-column prop="startTime" label="开始时间"/><el-table-column prop="endTime" label="结束时间"/><el-table-column prop="status" label="状态"/></el-table></div></div></template>
<style scoped>.page{display:grid;gap:20px;animation:fadeIn .3s ease}.panel{background:var(--bs-card-bg);border-radius:8px;box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}header{margin-bottom:18px}header h3{margin:0;color:var(--bs-text-title)}.current{display:flex;justify-content:space-between;align-items:center}.current h2{margin:8px 0}.current p,.muted{color:var(--bs-text-muted);font-size:13px}.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.plan{border:1px solid var(--bs-border-color);border-radius:8px;padding:20px;display:flex;flex-direction:column;gap:12px}.plan h3{margin:0}.plan p{color:var(--bs-text-secondary);min-height:40px}.plan strong{font-size:28px;color:var(--bs-primary)}.plan small{color:var(--bs-text-muted)}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
