<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { getOrderList } from '../../../api/user/orders'
import { createReview, getMyReviews } from '../../../api/user/reviews'
import { orderLabel } from '../../../utils/display'
import { ElMessage } from 'element-plus'
const loading = ref(false); const orders = ref<any[]>([]); const reviews = ref<any[]>([]); const selectedOrderId = ref<number>(); const submitLoading = ref(false)
const form = ref({ ratingFood: 0, ratingDelivery: 0, ratingService: 0, content: '', isAnonymous: 0 })
const reviewedOrderIds = computed(() => new Set(reviews.value.map(r => r.orderId)))
const reviewableOrders = computed(() => orders.value.filter(o => o.orderStatus === 50 && !reviewedOrderIds.value.has(o.id)))
const fetchData = async () => { loading.value = true; try { const [orderRes, reviewRes] = await Promise.all([getOrderList({ page: 1, size: 100 }), getMyReviews({ page: 1, size: 100 })]); orders.value = orderRes.data?.list || []; reviews.value = reviewRes.data?.list || reviewRes.data || [] } catch { ElMessage.error('加载评价数据失败') } finally { loading.value = false } }
const submit = async () => { if (!selectedOrderId.value) return ElMessage.warning('请选择要评价的订单'); if (!form.value.ratingFood || !form.value.ratingDelivery || !form.value.ratingService) return ElMessage.warning('请完成三项评分'); if (!form.value.content.trim()) return ElMessage.warning('请输入评价内容'); submitLoading.value = true; try { await createReview(selectedOrderId.value, form.value as any); ElMessage.success('评价提交成功'); selectedOrderId.value = undefined; form.value = { ratingFood: 0, ratingDelivery: 0, ratingService: 0, content: '', isAnonymous: 0 }; await fetchData() } catch { ElMessage.error('评价提交失败') } finally { submitLoading.value = false } }
onMounted(fetchData)
</script>
<template><div class="page-container"><div class="card-panel"><div class="card-header"><div><h3>评价订单</h3><p>完成订单后可以评价菜品、配送和服务</p></div></div><el-empty v-if="!loading && !reviewableOrders.length" description="暂无待评价订单" /><el-form v-else label-width="90px" style="max-width:620px"><el-form-item label="订单"><el-select v-model="selectedOrderId" placeholder="选择已完成订单" style="width:100%"><el-option v-for="order in reviewableOrders" :key="order.id" :label="`${orderLabel(order.orderNo)} · ¥${order.payAmount}`" :value="order.id" /></el-select></el-form-item><el-form-item label="菜品评分"><el-rate v-model="form.ratingFood" /></el-form-item><el-form-item label="配送评分"><el-rate v-model="form.ratingDelivery" /></el-form-item><el-form-item label="服务评分"><el-rate v-model="form.ratingService" /></el-form-item><el-form-item label="评价内容"><el-input v-model="form.content" type="textarea" :rows="4" maxlength="500" show-word-limit placeholder="说说这次用餐体验" /></el-form-item><el-form-item label="匿名评价"><el-switch v-model="form.isAnonymous" :active-value="1" :inactive-value="0" /><span class="hint">开启后商家不会看到你的昵称</span></el-form-item><el-form-item><el-button type="primary" :loading="submitLoading" @click="submit">提交评价</el-button></el-form-item></el-form></div><div class="card-panel"><div class="card-header"><h3>我的评价</h3></div><el-empty v-if="!loading && !reviews.length" description="暂无评价记录" /><div v-for="review in reviews" :key="review.id" class="review"><div class="review-top"><span>{{ review.shopName || orderLabel(review.orderId) }}</span><strong>{{ review.overallRating || '-' }} 分</strong><small>{{ review.createTime?.slice(0,16) }}</small></div><p>{{ review.content }}</p><div class="scores">菜品 {{ review.ratingFood }} · 配送 {{ review.ratingDelivery }} · 服务 {{ review.ratingService }}</div><div v-if="review.merchantReply" class="reply">商家回复：{{ review.merchantReply }}</div></div></div></div></template>
<style scoped>.page-container{display:grid;gap:20px;animation:fadeIn .3s ease}.card-panel{background:var(--bs-card-bg);border-radius:var(--bs-radius-md);box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}.card-header{margin-bottom:20px}.card-header h3{margin:0;color:var(--bs-text-title)}.card-header p{margin:6px 0 0;color:var(--bs-text-muted);font-size:13px}.hint{margin-left:10px;color:var(--bs-text-muted);font-size:13px}.review{padding:16px 0;border-bottom:1px solid var(--bs-border-color)}.review:last-child{border-bottom:0}.review-top{display:flex;gap:16px;align-items:center}.review-top strong{color:var(--green)}.review-top small{margin-left:auto;color:var(--bs-text-muted)}.review p{margin:12px 0 8px;color:var(--bs-text-secondary);line-height:1.6}.scores{font-size:13px;color:var(--bs-text-muted)}.reply{margin-top:10px;padding:10px;background:var(--bs-bg-page);border-radius:6px;color:var(--bs-text-secondary)}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
