<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getComboList, getComboDetail, replaceComboDish, replaceCartComboDish } from '../../../api/user/combos'
import { getDishList } from '../../../api/user/dishes'
import { addToCart, getCartList } from '../../../api/user/cart'
import { ElMessage } from 'element-plus'
import { resolveFileUrl } from '../../../utils/fileUrl'

const loading = ref(false); const combos = ref<any[]>([]); const dishes = ref<any[]>([]); const detailVisible = ref(false); const detail = ref<any>(null); const rels = ref<any[]>([]); const replacements = ref<Record<number, number>>({}); const preview = ref<any>(null)
const fallbackImages = ['/images/home/meal-card.jpg', '/images/home/salad-card.jpg', '/images/home/hero-fresh-bowl.jpg']
const imageFor = (combo: any, index: number) => resolveFileUrl(combo.comboImage) || fallbackImages[index % fallbackImages.length]
const fetchData = async () => { loading.value = true; try { const [comboRes, dishRes] = await Promise.all([getComboList({ page: 1, size: 20 }), getDishList({ page: 1, size: 100 })]); combos.value = comboRes.data?.data?.list || []; dishes.value = dishRes.data?.data?.list || [] } catch { ElMessage.error('加载套餐失败') } finally { loading.value = false } }
const dishById = (id: number) => dishes.value.find(d => d.id === id)
const showDetail = async (row: any) => { try { const res = await getComboDetail(row.id); detail.value = res.data?.combo || row; rels.value = res.data?.dishRels || []; replacements.value = {}; preview.value = null; detailVisible.value = true } catch { ElMessage.error('获取套餐详情失败') } }
const replaceDish = async (rel: any, newId: number) => { if (!newId || newId === rel.dishId) return; try { const res = await replaceComboDish(detail.value.id, rel.dishId, newId); replacements.value[rel.dishId] = newId; preview.value = res.data || res; ElMessage.success('已更新套餐营养数据') } catch { ElMessage.error('该菜品暂不可替换') } }
const addCombo = async () => { try { await addToCart(20, undefined, detail.value.id, 1); const cartRes = await getCartList(); const cart = (cartRes.data || []).find((item: any) => item.comboId === detail.value.id); for (const [oldId, newId] of Object.entries(replacements.value)) { if (cart) await replaceCartComboDish(cart.id, Number(oldId), newId) } ElMessage.success('套餐已加入购物车'); detailVisible.value = false } catch { ElMessage.error('加入购物车失败') } }
onMounted(fetchData)
</script>
<template>
  <div class="combo-page"><header class="combo-intro"><span>健康套餐</span><h1>把一日营养，<br />安排得恰到好处。</h1><p>减脂、增肌或控糖，从适合你的组合开始。</p></header><div v-loading="loading" class="combo-grid"><article v-for="(combo,index) in combos" :key="combo.id" class="combo-card"><button class="combo-image" @click="showDetail(combo)"><img :src="imageFor(combo,index)" :alt="combo.comboName" /><span>{{ combo.totalCalories || 0 }} kcal</span></button><div class="combo-body"><div class="combo-title"><h2>{{ combo.comboName }}</h2><strong>¥{{ combo.price }}</strong></div><p>{{ combo.description || '为日常目标准备的均衡搭配。' }}</p><div class="nutrition"><span>蛋白 {{ combo.totalProtein || 0 }}g</span><span>碳水 {{ combo.totalCarbs || 0 }}g</span></div><button class="combo-action" @click="showDetail(combo)">查看套餐 <span>→</span></button></div></article><div v-if="!loading && !combos.length" class="combo-empty"><img src="/images/home/meal-card.jpg" alt="健康套餐" /><div><h2>套餐正在准备</h2><p>完成健康档案，获得更适合你的搭配。</p></div></div></div>
  <el-dialog v-model="detailVisible" title="套餐详情" width="680px"><template v-if="detail"><div class="detail-head"><el-image v-if="detail.comboImage" :src="detail.comboImage" fit="cover" class="detail-image" /><div><h2>{{ detail.comboName }}</h2><p>{{ detail.description || '暂无描述' }}</p><strong class="price">¥{{ detail.price }}</strong></div></div><div class="section-title">套餐内容</div><div v-for="rel in rels" :key="rel.id" class="dish-row"><div class="dish-info"><el-image v-if="dishById(rel.dishId)?.dishImage" :src="dishById(rel.dishId)?.dishImage" fit="cover" class="dish-image" /><span>{{ dishById(rel.dishId)?.dishName || `菜品 #${rel.dishId}` }} × {{ rel.quantity || 1 }}</span><el-tag v-if="rel.isFixed === 1" size="small" type="info">固定</el-tag></div><el-select v-if="rel.isFixed !== 1" :model-value="replacements[rel.dishId] || rel.dishId" placeholder="选择替换菜品" style="width:220px" @change="(id: number) => replaceDish(rel, id)"><el-option v-for="dish in dishes" :key="dish.id" :label="dish.dishName" :value="dish.id" /></el-select></div><el-alert v-if="preview" title="替换后营养已重新计算" type="success" :closable="false" style="margin-top:16px"><template #default>热量 {{ preview.totalCalories || 0 }} kcal，蛋白质 {{ preview.totalProtein || 0 }}g，脂肪 {{ preview.totalFat || 0 }}g，碳水 {{ preview.totalCarbs || 0 }}g</template></el-alert></template><template #footer><el-button @click="detailVisible = false">关闭</el-button><el-button type="primary" @click="addCombo">加入购物车</el-button></template></el-dialog>
  </div>
</template>
<style scoped>.combo-page{max-width:1192px;margin:0 auto;padding:66px 24px 90px;color:#1f2a24}.combo-intro{display:grid;grid-template-columns:1fr 1fr;align-items:end;margin-bottom:42px}.combo-intro span{grid-column:1;color:#cf704f;font-size:12px;font-weight:650;letter-spacing:.14em}.combo-intro h1{grid-column:1;margin:12px 0 0;font-family:"Source Han Serif SC","Songti SC",serif;font-size:38px;line-height:1.2;font-weight:600}.combo-intro p{grid-column:2;margin:0 0 6px;max-width:270px;color:#6d7971;font-size:14px;line-height:1.7}.combo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:28px 22px;min-height:300px}.combo-card{background:#fff;border-bottom:1px solid #dfe7df}.combo-image{position:relative;width:100%;height:240px;padding:0;border:0;background:#eef2ed;overflow:hidden;cursor:pointer}.combo-image img{width:100%;height:100%;object-fit:cover;transition:transform .35s}.combo-card:hover .combo-image img{transform:scale(1.04)}.combo-image span{position:absolute;right:12px;bottom:12px;padding:5px 8px;background:#fff;color:#1f4d3a;font-size:11px}.combo-body{padding:17px 2px}.combo-title{display:flex;justify-content:space-between;gap:12px}.combo-title h2{margin:0;font-size:18px}.combo-title strong{color:#1f4d3a;font-size:17px}.combo-body p{min-height:38px;margin:9px 0;color:#718078;font-size:12px;line-height:1.6}.nutrition{display:flex;gap:15px;color:#78857d;font-size:11px}.combo-action{margin-top:16px;padding:0;border:0;background:none;color:#1f4d3a;font-weight:650;cursor:pointer}.combo-action span{margin-left:6px;color:#cf704f}.combo-empty{grid-column:1/-1;display:flex;align-items:center;justify-content:center;gap:28px;min-height:280px;background:#eff3ee}.combo-empty img{width:145px;height:145px;object-fit:cover}.combo-empty h2{margin:0 0 8px;font-family:"Source Han Serif SC","Songti SC",serif}.combo-empty p{margin:0;color:#718078;font-size:13px}.detail-head{display:flex;gap:18px}.detail-image{width:180px;height:130px;border-radius:8px;background:#f3f5f7}.detail-head h2{margin:0 0 10px}.detail-head p{color:#6d7971;line-height:1.6}.section-title{font-weight:600;margin:20px 0 10px}.dish-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #edf0f2}.dish-info{display:flex;align-items:center;gap:10px}.dish-image{width:42px;height:42px;border-radius:6px;background:#f3f5f7;flex-shrink:0}@media(max-width:800px){.combo-page{padding:45px 18px 68px}.combo-grid{grid-template-columns:repeat(2,1fr)}.combo-intro{grid-template-columns:1fr}.combo-intro p{grid-column:1;margin-top:15px}.combo-image{height:210px}}@media(max-width:540px){.combo-grid{grid-template-columns:1fr}.combo-intro h1{font-size:31px}.combo-image{height:250px}}</style>
