<script setup lang="ts">
import { ref } from 'vue'
import { aiRecommend } from '../../../api/user/ai'
import { ElMessage } from 'element-plus'
const loading=ref(false), result=ref<any>(null), mealType=ref(''), restrictions=ref('')
const generate=async()=>{loading.value=true;try{const p:any={};if(mealType.value)p.mealType=mealType.value;if(restrictions.value)p.dietaryRestrictions=restrictions.value;const r=await aiRecommend(p);result.value=r.data}catch{ElMessage.error('获取推荐失败')}finally{loading.value=false}}
</script>
<template><div class="page"><div class="panel"><header><div><h3>AI 食谱推荐</h3><p>推荐会读取健康档案和营养标准</p></div><el-button type="primary" :loading="loading" @click="generate">生成推荐</el-button></header><div class="filters"><el-select v-model="mealType" clearable placeholder="选择餐次"><el-option label="早餐" value="breakfast"/><el-option label="午餐" value="lunch"/><el-option label="晚餐" value="dinner"/></el-select><el-input v-model="restrictions" clearable placeholder="饮食限制，如低糖、海鲜过敏"/></div><div v-loading="loading" class="result"><el-alert v-if="result?.success===false" :title="result.message" type="warning" :closable="false"/><template v-else-if="result"><div class="stats"><div>目标<strong>{{result.healthGoal||'-'}}</strong></div><div>每日热量<strong>{{result.dailyCalories||'-'}}</strong></div><div>蛋白质<strong>{{result.proteinGrams||'-'}}g</strong></div><div>脂肪<strong>{{result.fatGrams||'-'}}g</strong></div><div>碳水<strong>{{result.carbsGrams||'-'}}g</strong></div></div><article>{{result.recommendation||'暂无推荐内容'}}</article></template><el-empty v-else-if="!loading" description="填写健康档案后生成个性化推荐"/></div></div></div></template>
<style scoped>.page{animation:fadeIn .3s ease}.panel{background:var(--bs-card-bg);border-radius:var(--bs-radius-md);box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}h3{margin:0;color:var(--bs-text-title)}p{margin:6px 0 0;color:var(--bs-text-muted);font-size:13px}.filters{display:flex;gap:12px;max-width:620px}.filters .el-input{flex:1}.result{min-height:260px;margin-top:24px}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.stats div{padding:14px;background:#f7f8fa;border-radius:8px;color:var(--bs-text-muted);font-size:13px}.stats strong{display:block;margin-top:8px;color:var(--bs-text-title)}article{white-space:pre-wrap;line-height:1.8;padding:20px 0;color:var(--bs-text-secondary)}@media(max-width:700px){.filters{flex-wrap:wrap}.stats{grid-template-columns:repeat(2,1fr)}}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
