<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getComplaintList, handleComplaint, getComplaintDetail } from '../../api/admin/work-orders'
import ListState from '../../components/common/ListState.vue'
const loading=ref(false); const rows=ref<any[]>([]); const total=ref(0); const pageNum=ref(1); const pageSize=ref(10); const status=ref<number|undefined>()
const dialog=ref(false); const current=ref<any>(); const remark=ref(''); const result=ref('')
const detailDialog=ref(false); const detail=ref<any>()
const loadError=ref('')
const statusMap:Record<number,string>={10:'待处理',20:'处理中',30:'已完成',40:'已驳回'}
const load=async()=>{loading.value=true;loadError.value='';try{const r=await getComplaintList({pageNum:pageNum.value,pageSize:pageSize.value,status:status.value});if(r.code===200){rows.value=r.data.list||[];total.value=r.data.total||0}else{loadError.value=r.message||'投诉工单暂时无法获取';ElMessage.error(loadError.value)}}catch(err){loadError.value='请检查网络连接后重试';ElMessage.error(loadError.value);console.error('获取投诉工单失败',err)}finally{loading.value=false}}
const open=(row:any)=>{current.value=row;remark.value='';result.value='';dialog.value=true}
const openDetail=async(row:any)=>{const r=await getComplaintDetail(row.id);if(r.code===200){detail.value=r.data;detailDialog.value=true}}
const evidenceImages=(value:any):string[]=>{if(!value)return[];try{const parsed=typeof value==='string'?JSON.parse(value):value;return Array.isArray(parsed)?parsed:[]}catch{return[]}}
const imageUrl=(value:string)=>value?.startsWith('http')?value:`/api/files/download${value}`
const submit=async(next:number)=>{const r=await handleComplaint(current.value.id,next,remark.value,result.value);if(r.code===200){ElMessage.success('投诉工单已处理');dialog.value=false;load()}}
onMounted(load)
</script>
<template><div class="page-container"><div class="card-panel"><div class="card-header"><h3>投诉工单</h3><el-select v-model="status" clearable placeholder="按状态筛选" size="small" style="width:150px" @change="load"><el-option v-for="(label,value) in statusMap" :key="value" :label="label" :value="Number(value)"/></el-select></div><el-table :data="rows" v-loading="loading" border stripe><el-table-column prop="orderId" label="订单ID" width="100"/><el-table-column prop="targetId" label="被投诉对象" width="120"/><el-table-column prop="complaintReason" label="投诉原因" min-width="180"/><el-table-column prop="complaintDesc" label="详情" min-width="220" show-overflow-tooltip/><el-table-column label="状态" width="100"><template #default="{row}">{{statusMap[row.status]||'-'}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button type="primary" link size="small" @click="openDetail(row)">详情</el-button><el-button v-if="row.status===10||row.status===20" type="primary" link size="small" @click="open(row)">处理</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="pageNum" v-model:page-size="pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></div></div><el-dialog v-model="dialog" title="处理投诉工单" width="460px"><el-input v-model="remark" type="textarea" :rows="2" placeholder="管理员备注"/><el-input v-model="result" type="textarea" :rows="3" placeholder="处理结果" style="margin-top:12px"/><template #footer><el-button @click="dialog=false">关闭</el-button><el-button type="warning" @click="submit(40)">驳回</el-button><el-button type="primary" @click="submit(30)">完成处理</el-button></template></el-dialog><el-dialog v-model="detailDialog" title="投诉工单详情" width="620px"><el-descriptions v-if="detail" :column="2" border><el-descriptions-item label="订单号">{{ detail.order?.orderNo || detail.workOrder?.orderId || '-' }}</el-descriptions-item><el-descriptions-item label="用户">{{ detail.user?.nickname || detail.user?.username || detail.workOrder?.userId || '-' }}</el-descriptions-item><el-descriptions-item label="商家">{{ detail.merchant?.shopName || detail.order?.merchantId || '-' }}</el-descriptions-item><el-descriptions-item label="投诉对象">{{ detail.workOrder?.targetId || '-' }}</el-descriptions-item><el-descriptions-item label="投诉原因" :span="2">{{ detail.workOrder?.complaintReason || '-' }}</el-descriptions-item><el-descriptions-item label="详细说明" :span="2">{{ detail.workOrder?.complaintDesc || '-' }}</el-descriptions-item><el-descriptions-item label="处理结果" :span="2">{{ detail.workOrder?.result || '暂未处理' }}</el-descriptions-item><el-descriptions-item label="管理员备注" :span="2">{{ detail.workOrder?.adminRemark || '-' }}</el-descriptions-item></el-descriptions></el-dialog></div></template>
<style scoped>.page-container{animation:fadeIn .25s ease}.card-panel{background:#fff;border:1px solid var(--bs-border-light);border-radius:8px;padding:20px;box-shadow:var(--bs-card-shadow)}.card-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.card-header h3{margin:0;color:var(--bs-text-title)}.pager{display:flex;justify-content:flex-end;margin-top:16px}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}</style>
