<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { getDishList } from '../../api/user/dishes'
import { getComboList } from '../../api/user/combos'
import { addToCart } from '../../api/user/cart'
import { ElMessage } from 'element-plus'
const router=useRouter(), loading=ref(false), dishes=ref<any[]>([]), combos=ref<any[]>([])
const load=async()=>{loading.value=true;try{const [d,c]=await Promise.all([getDishList({page:1,size:6}),getComboList({page:1,size:3})]);dishes.value=d.data?.list||[];combos.value=c.data?.list||[]}catch{ElMessage.error('加载首页数据失败')}finally{loading.value=false}}
const add=async(d:any)=>{try{await addToCart(10,d.id,undefined,1);ElMessage.success('已加入购物车')}catch{ElMessage.error('加入购物车失败')}}
onMounted(load)
</script>
<template><div class="page"><section class="welcome"><div><span class="eyebrow">BiteSmart · 健康饮食</span><h1>今天，吃得更适合自己</h1><p>从营养搭配到配送到家，让每一餐都更轻松。</p><div class="actions"><el-button type="primary" @click="router.push('/user/ai/recommend')">生成今日食谱</el-button><el-button @click="router.push('/user/combos')">浏览健康套餐</el-button></div></div></section><section class="panel"><header><h3>推荐菜品</h3><el-button link @click="router.push('/user/dishes')">查看全部</el-button></header><el-table v-loading="loading" :data="dishes" border><el-table-column label="菜品" min-width="220"><template #default="{row}"><div class="dish"><el-image v-if="row.dishImage" :src="row.dishImage" fit="cover"/><span>{{row.dishName}}</span></div></template></el-table-column><el-table-column label="价格" width="110"><template #default="{row}">¥{{row.price}}</template></el-table-column><el-table-column prop="calories" label="热量(kcal)" width="120"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button size="small" type="primary" @click="add(row)">加入购物车</el-button></template></el-table-column></el-table></section><section class="panel"><header><h3>健康套餐</h3><el-button link @click="router.push('/user/combos')">查看全部</el-button></header><div class="combos"><div v-for="combo in combos" :key="combo.id" class="combo"><el-image v-if="combo.comboImage" :src="combo.comboImage" fit="cover"/><div><strong>{{combo.comboName}}</strong><p>{{combo.description||'营养均衡的健康搭配'}}</p><b>¥{{combo.price}}</b></div></div></div></section></div></template>
<style scoped>.page{display:grid;gap:20px;animation:fadeIn .3s ease}.welcome{padding:32px;background:#e9f3ee;border-radius:8px}.eyebrow{font-size:13px;color:#47735e}.welcome h1{margin:12px 0 8px;color:#1b3a2f;font-size:30px}.welcome p{color:#527264}.actions{display:flex;gap:10px;margin-top:22px}.panel{background:var(--bs-card-bg);border-radius:8px;box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}header h3{margin:0;color:var(--bs-text-title)}.dish{display:flex;align-items:center;gap:12px}.dish .el-image{width:44px;height:44px;border-radius:6px;background:#f3f5f7}.combos{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.combo{display:flex;gap:12px;padding:12px;border:1px solid var(--bs-border-color);border-radius:8px}.combo .el-image{width:80px;height:70px;border-radius:6px;background:#f3f5f7;flex-shrink:0}.combo strong{color:var(--bs-text-title)}.combo p{font-size:13px;color:var(--bs-text-muted);margin:6px 0}.combo b{color:var(--bs-primary)}@media(max-width:700px){.combos{grid-template-columns:1fr}.welcome h1{font-size:24px}}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
