<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getCurrentUser, getProfile, saveProfile } from '../../../api/user/profile'
import { ElMessage } from 'element-plus'
const loading=ref(false), editing=ref(false), user=ref<any>({}), form=ref<any>({age:0,gender:0,height:0,weight:0,activityLevel:10,dietPreference:'',allergyInfo:'',diseaseHistory:'',healthGoal:''})
const goals=['减脂','增肌','维持','控糖','其他'];const activities=[{label:'久坐',value:10},{label:'轻度运动',value:20},{label:'中度运动',value:30},{label:'高强度运动',value:40}]
const load=async()=>{loading.value=true;try{const [u,p]=await Promise.all([getCurrentUser(),getProfile()]);user.value=u.data||{};form.value={...form.value,...(p.data||{})}}catch{ElMessage.error('加载个人档案失败')}finally{loading.value=false}}
const save=async()=>{loading.value=true;try{await saveProfile(form.value);ElMessage.success('档案已保存');editing.value=false;load()}catch{ElMessage.error('保存失败')}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page"><div class="panel"><header><h3>个人中心</h3><div><el-button v-if="editing" @click="editing=false">取消</el-button><el-button type="primary" :loading="loading" @click="editing?save():editing=true">{{editing?'保存':'编辑'}}</el-button></div></header><el-form v-loading="loading" label-width="110px"><el-form-item label="用户名"><el-input :model-value="user.username" disabled/></el-form-item><el-form-item label="昵称"><span>{{user.nickname||'未设置'}}</span></el-form-item><el-divider>健康档案</el-divider><el-form-item label="年龄"><el-input-number v-if="editing" v-model="form.age" :min="1" :max="150"/><span v-else>{{form.age||'未设置'}}</span></el-form-item><el-form-item label="性别"><el-select v-if="editing" v-model="form.gender"><el-option label="男" :value="10"/><el-option label="女" :value="20"/></el-select><span v-else>{{form.gender===10?'男':form.gender===20?'女':'未设置'}}</span></el-form-item><el-form-item label="身高(cm)"><el-input-number v-if="editing" v-model="form.height" :min="50" :max="250"/><span v-else>{{form.height||'未设置'}}</span></el-form-item><el-form-item label="体重(kg)"><el-input-number v-if="editing" v-model="form.weight" :min="20" :max="300" :precision="1"/><span v-else>{{form.weight||'未设置'}}</span></el-form-item><el-form-item label="活动水平"><el-select v-if="editing" v-model="form.activityLevel"><el-option v-for="a in activities" :key="a.value" :label="a.label" :value="a.value"/></el-select><span v-else>{{activities.find(a=>a.value===form.activityLevel)?.label||'未设置'}}</span></el-form-item><el-form-item label="健康目标"><el-select v-if="editing" v-model="form.healthGoal"><el-option v-for="g in goals" :key="g" :label="g" :value="g"/></el-select><span v-else>{{form.healthGoal||'未设置'}}</span></el-form-item><el-form-item label="饮食偏好"><el-input v-if="editing" v-model="form.dietPreference" placeholder="如：少盐、素食"/><span v-else>{{form.dietPreference||'无'}}</span></el-form-item><el-form-item label="过敏信息"><el-input v-if="editing" v-model="form.allergyInfo"/><span v-else>{{form.allergyInfo||'无'}}</span></el-form-item><el-form-item label="疾病史"><el-input v-if="editing" v-model="form.diseaseHistory"/><span v-else>{{form.diseaseHistory||'无'}}</span></el-form-item></el-form></div></div></template>
<style scoped>.page{animation:fadeIn .3s ease}.panel{background:var(--bs-card-bg);border-radius:8px;box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}header h3{margin:0;color:var(--bs-text-title)}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
