<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { getDeliveryTracking } from '../../../api/user/delivery'
import { ElMessage } from 'element-plus'
const route = useRoute(); const loading = ref(false); const tracking = ref<any>(null); let timer: ReturnType<typeof setInterval> | undefined
const statusMap: Record<number, string> = { 10: '待分配', 20: '待取餐', 30: '已取餐', 40: '配送中', 50: '已送达', 60: '配送异常', 70: '已取消' }
const fetchTracking = async () => { const id = Number(route.params.orderId); if (!id) return; loading.value = !tracking.value; try { const res = await getDeliveryTracking(id); tracking.value = res.data } catch { if (!tracking.value) ElMessage.error('暂时无法获取配送信息') } finally { loading.value = false } }
onMounted(() => { fetchTracking(); timer = setInterval(fetchTracking, 10000) }); onUnmounted(() => { if (timer) clearInterval(timer) })
</script>
<template><div class="page-container"><div class="card-panel"><div class="card-header"><div><h3>配送详情</h3><p>页面会自动更新配送状态</p></div><el-button @click="fetchTracking">刷新</el-button></div><div v-loading="loading" class="content"><template v-if="tracking"><el-steps :active="tracking.taskStatus >= 50 ? 3 : tracking.taskStatus >= 40 ? 2 : tracking.taskStatus >= 30 ? 1 : 0" finish-status="success" align-center><el-step title="等待取餐" /><el-step title="已取餐" /><el-step title="配送中" /><el-step title="已送达" /></el-steps><el-alert :title="statusMap[tracking.taskStatus] || '配送状态更新中'" :type="tracking.taskStatus === 60 ? 'error' : tracking.taskStatus >= 50 ? 'success' : 'warning'" :closable="false" style="margin-top:24px" /><el-descriptions :column="2" border style="margin-top:18px"><el-descriptions-item label="取餐码">{{ tracking.pickupCode || '暂无' }}</el-descriptions-item><el-descriptions-item label="预计送达">{{ tracking.estimatedDeliveryTime || '待确认' }}</el-descriptions-item><el-descriptions-item label="取餐时间">{{ tracking.pickupTime || '尚未取餐' }}</el-descriptions-item><el-descriptions-item label="送达时间">{{ tracking.deliverTime || '尚未送达' }}</el-descriptions-item><el-descriptions-item label="当前位置" :span="2">{{ tracking.currentLat && tracking.currentLng ? `${tracking.currentLat}, ${tracking.currentLng}` : '配送员尚未上传位置' }}</el-descriptions-item></el-descriptions><div v-if="tracking.driver" class="driver"><div><strong>{{ tracking.driver.realName || '配送员' }}</strong><span>{{ tracking.driver.vehicleType || '配送中' }}</span></div><a :href="`tel:${tracking.driver.phone}`">{{ tracking.driver.phone }}</a></div></template><el-empty v-else-if="!loading" description="暂无配送任务，商家出餐后会自动创建" /></div></div></div></template>
<style scoped>.page-container{animation:fadeIn .3s ease}.card-panel{background:var(--bs-card-bg);border-radius:var(--bs-radius-md);box-shadow:var(--bs-card-shadow);padding:var(--bs-spacing-lg)}.card-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.card-header h3{margin:0;color:var(--bs-text-title)}.card-header p{margin:6px 0 0;color:var(--bs-text-muted);font-size:13px}.content{min-height:220px}.driver{display:flex;justify-content:space-between;align-items:center;margin-top:18px;padding:16px;background:#f7f8fa;border-radius:8px}.driver div{display:flex;gap:12px;align-items:center}.driver span{font-size:13px;color:var(--bs-text-muted)}.driver a{color:var(--bs-primary)}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}</style>
