CREATE TABLE IF NOT EXISTS merchant_fund_account (
  id bigint NOT NULL COMMENT '主键ID',
  merchant_id bigint NOT NULL COMMENT '商家ID',
  pending_balance decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '待结算余额',
  available_balance decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '可结算余额',
  frozen_balance decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '冻结余额',
  total_income decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '累计收入',
  total_refund decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '累计退款',
  total_commission decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '累计平台佣金',
  version bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_merchant_id (merchant_id),
  KEY idx_account_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家资金账户';

CREATE TABLE IF NOT EXISTS merchant_fund_ledger (
  id bigint NOT NULL COMMENT '主键ID',
  merchant_id bigint NOT NULL COMMENT '商家ID',
  order_id bigint DEFAULT NULL COMMENT '订单ID',
  payment_log_id bigint DEFAULT NULL COMMENT '支付流水ID',
  refund_id bigint DEFAULT NULL COMMENT '退款工单ID',
  settlement_id bigint DEFAULT NULL COMMENT '结算批次ID',
  ledger_type tinyint NOT NULL COMMENT '流水类型：10收入 20佣金 30退款冲正 40结算',
  direction tinyint NOT NULL COMMENT '方向：10增加 20减少',
  balance_scope tinyint NOT NULL COMMENT '余额范围：10待结算 20可结算',
  amount decimal(12,2) NOT NULL COMMENT '发生金额，正数',
  balance_before decimal(12,2) NOT NULL COMMENT '变更前余额',
  balance_after decimal(12,2) NOT NULL COMMENT '变更后余额',
  idempotency_key varchar(128) NOT NULL COMMENT '业务幂等键',
  status tinyint NOT NULL DEFAULT '20' COMMENT '状态：10处理中 20已完成 30已冲正',
  remark varchar(255) DEFAULT NULL COMMENT '备注',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ledger_idempotency (idempotency_key),
  KEY idx_ledger_merchant_time (merchant_id, create_time),
  KEY idx_ledger_order_id (order_id),
  KEY idx_ledger_refund_id (refund_id),
  KEY idx_ledger_settlement_id (settlement_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家资金流水';

CREATE TABLE IF NOT EXISTS merchant_settlement (
  id bigint NOT NULL COMMENT '主键ID',
  merchant_id bigint NOT NULL COMMENT '商家ID',
  settlement_no varchar(32) NOT NULL COMMENT '结算单号',
  period_start datetime DEFAULT NULL COMMENT '结算周期开始',
  period_end datetime DEFAULT NULL COMMENT '结算周期结束',
  gross_amount decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '收入总额',
  commission_amount decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '平台佣金',
  refund_amount decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '退款冲正',
  net_amount decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '结算净额',
  settlement_status tinyint NOT NULL DEFAULT '10' COMMENT '状态：10待审核 20已审核 30已结算 40已驳回',
  payout_method varchar(32) DEFAULT NULL COMMENT '结算方式',
  payout_account_mask varchar(128) DEFAULT NULL COMMENT '收款账户脱敏信息',
  operator_id bigint DEFAULT NULL COMMENT '操作人ID',
  operator_remark varchar(255) DEFAULT NULL COMMENT '操作备注',
  paid_time datetime DEFAULT NULL COMMENT '结算完成时间',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_settlement_no (settlement_no),
  KEY idx_settlement_merchant_time (merchant_id, create_time),
  KEY idx_settlement_status (settlement_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家结算批次';
